### ISSUE TITLE
Detected by Defender + Skylake CPU at 100% then crash

### ISSUE THREAD

**Issue by MrRocketFX** [fox32-arch/fox32#1]
All versions appear to be detected by defender.

And on my Skylake desktop the CPU goes to 100% locks up everything for 30ms then fox32 crashes.

**Comment by ry755** [comment]
Huh that's really weird, I'll have to look into that more because honestly I have no idea what could be causing that.
The Windows builds (assuming you're on Windows because you mentioned defender) are built automatically by GitHub Actions, not built locally by me. I'll have to check to make sure it's getting built properly.

**Comment by ry755** [comment]
If possible, could you please try compiling it yourself and see if the issue still exists? Install the Rust toolchain and then follow the instructions in this repo's readme.
I'm still not sure what could be causing it to lock up and crash, it works for me on all of the Windows machines that I've tested it on.
As for the defender issue, maybe that's just because the binaries aren't signed? Are they actually getting detected as viruses or is defender just showing a "be careful" pop-up when you try running it?
